### ISSUE TITLE
Handle output for multiples jobs in task

### ISSUE THREAD

**Issue by cempassi** [cempassi/taskmaster#80]

**Comment by FirelightFlagboy** [comment]
We could use a pattern string for multiple output file.

We could use the sequence `#` that designate the PID of the running subprocess
```yaml
stdout: /tmp/output-#.log
``` 
Would write `/tmp/output-123.log` for a process of `PID = 123`

And by **default**, we could append the PID at the end of the filename (or do nothing).
Again with a process of `PID = 123` with `stdout = /tmp/output.log` we will output `/tmp/stdout.log123`

**Comment by FirelightFlagboy** [comment]
Force use of a template for the time being, even for task that spawn 1 process

**Comment by FirelightFlagboy** [comment]
rust come with [`String.replace`](https://doc.rust-lang.org/std/string/struct.String.html#method.replace)

with that, we can use more complicated template format

| Name | Description |
| --- | --- |
| Num | number of the current process |
| Time | timestamp of the execution |
